config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to article_url(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to article_url(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :body
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_with model: @article do |f| %>
  <%= link_to "Back", article_path(@article) %>

  <%#= タイトル %>
  <div>
    <% frame_id = dom_id(@article, "title_turbo_frame") %>

    <turbo-frame id="<%= frame_id %>">
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%# スタイルをうまいこと当ててやらないと普通の編集フォームでも保存ボタンやキャンセルボタンが表示されてしまう %>
      <%= f.button class: "hidden inline-edit:inline" do %>
        Save <%= @article.class.human_attribute_name(:title) %>
      <% end %>
      <%= link_to "Cancel", polymorphic_path(@article), class: "hidden inline-edit:inline"  %>
    </turbo-frame>
  </div>

  <%#= 本文 %>
  <div>
    <% frame_id = dom_id(@article, "body_turbo_frame") %>

    <turbo-frame id="<%= frame_id %>">
      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.button class: "hidden inline-edit:inline"   do %>
        Save <%= @article.class.human_attribute_name(:body) %>
      <% end %>
      <%= link_to "Cancel", polymorphic_path(@article), class: "hidden inline-edit:inline" %>
    </turbo-frame>
  </div>

  <%= f.button %>
<% end %>

app/views/articles/index.html.erb
<%= link_to '新規作成', new_article_path %>

<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<%= form_with model: @article do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<%= link_to "Edit Article", edit_article_path(@article) %> |
<%= link_to "Index Articles", articles_path %>

<% frame_id = dom_id(@article, "title_turbo_frame") %>

<%= form_with model: @article, data: { turbo_frame: frame_id } do %>
  <h1>タイトル</h1>
  <turbo-frame id="<%= frame_id %>" class="inline-edit">
    <h2><%= @article.title %></h2>

    <%= link_to edit_polymorphic_path(@article) do %>
      Edit <%= @article.class.human_attribute_name(:title) %>
    <% end %>
  </turbo-frame>
<% end %>


<% frame_id = dom_id(@article, "body_turbo_frame") %>

<%= form_with model: @article, data: { turbo_frame: frame_id } do %>
  <h1>本文</h1>
  <turbo-frame id="<%= frame_id %>" class="inline-edit">
    <h1><%= @article.body %></h1>

    <%= link_to edit_polymorphic_path(@article) do %>
      Edit <%= @article.class.human_attribute_name(:body) %>
    <% end %>
  </turbo-frame>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireInlineForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>